// <auto-generated />
using System;
using ContactsApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ContactsApi.Database.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20201219124524_ContactsSeedData")]
    partial class ContactsSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ContactsApi.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreatedOrUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_or_updated");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("first_name");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("FirstName", "Surname")
                        .HasDatabaseName("contact_uidx");

                    b.ToTable("contacts");

                    b
                        .HasComment("Data about contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOrUpdated = new DateTime(2020, 12, 19, 13, 45, 23, 715, DateTimeKind.Local).AddTicks(231),
                            DateOfBirth = new DateTime(1964, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Keanu",
                            Surname = "Reeves"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOrUpdated = new DateTime(2020, 12, 19, 13, 45, 23, 719, DateTimeKind.Local).AddTicks(3177),
                            DateOfBirth = new DateTime(1981, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Roger",
                            Surname = "Federer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOrUpdated = new DateTime(2020, 12, 19, 13, 45, 23, 719, DateTimeKind.Local).AddTicks(3226),
                            DateOfBirth = new DateTime(1971, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            Surname = "Wahlberg"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOrUpdated = new DateTime(2020, 12, 19, 13, 45, 23, 719, DateTimeKind.Local).AddTicks(3231),
                            FirstName = "Superman"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOrUpdated = new DateTime(2020, 12, 19, 13, 45, 23, 719, DateTimeKind.Local).AddTicks(3236),
                            DateOfBirth = new DateTime(1955, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bill",
                            Surname = "Gates"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
